# Generated by Django 6.0.4 on 2026-08-09 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario_nombre', models.CharField(max_length=150, verbose_name='nombre en ese momento')),
                ('accion', models.CharField(choices=[('crear_usuario', 'Creó un usuario'), ('editar_usuario', 'Editó un usuario'), ('activar_usuario', 'Activó un usuario'), ('desactivar_usuario', 'Desactivó un usuario'), ('resetear_password', 'Restableció una contraseña'), ('cambiar_rol', 'Cambió el rol de un usuario'), ('crear_rol', 'Creó un rol'), ('editar_rol', 'Modificó un rol'), ('eliminar_rol', 'Eliminó un rol')], max_length=40)),
                ('objetivo', models.CharField(blank=True, max_length=200, verbose_name='sobre quién o qué')),
                ('detalle', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_auditadas', to=settings.AUTH_USER_MODEL, verbose_name='quién lo hizo')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-fecha'],
                'default_permissions': ('view',),
            },
        ),
    ]
