# Generated by Django 6.0.4 on 2026-08-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinica'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clinica',
            table='Clinica',
        ),
        migrations.AlterModelTable(
            name='registroauditoria',
            table='RegistroAuditoria',
        ),
    ]
