# Generated by Django 6.0.4 on 2026-09-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clinica_table_alter_registroauditoria_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('crear_usuario', 'Creó un usuario'), ('editar_usuario', 'Editó un usuario'), ('activar_usuario', 'Activó un usuario'), ('desactivar_usuario', 'Desactivó un usuario'), ('resetear_password', 'Restableció una contraseña'), ('cambiar_rol', 'Cambió el rol de un usuario'), ('crear_rol', 'Creó un rol'), ('editar_rol', 'Modificó un rol'), ('eliminar_rol', 'Eliminó un rol'), ('editar_preconsulta', 'Corrigió una preconsulta')], max_length=40),
        ),
    ]
