# Generated by Django 6.0.4 on 2026-09-15 20:47

import unicodedata

from django.db import migrations, models


def _normalizar(texto):
    sin_tildes = unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode()
    return sin_tildes.lower()


def clasificar_clinicas(apps, schema_editor):
    """Marca como estetica la clinica que ya existia con ese nombre y llena el logo de cada una."""
    Clinica = apps.get_model('core', 'Clinica')
    for clinica in Clinica.objects.all():
        nombre = _normalizar(clinica.nombre)
        if 'estetica' in nombre:
            clinica.tipo = 'estetica'
            clinica.tema = 'estetica'
            if not clinica.logo:
                clinica.logo = 'core/img/logo_estetica.svg'
        if 'prosalud' in nombre.replace(' ', '') and not clinica.logo:
            clinica.logo = 'core/img/logo_prosalud.svg'
        clinica.save(update_fields=['tipo', 'tema', 'logo'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registroauditoria_editar_preconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='tema',
            field=models.CharField(choices=[('verde_salud', 'Verde salud'), ('estetica', 'Estética')], default='verde_salud', max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='tipo',
            field=models.CharField(choices=[('medica', 'Clínica médica'), ('estetica', 'Clínica estética')], default='medica', max_length=20),
        ),
        # Sin reversa de datos: al deshacer, las columnas se eliminan igual.
        migrations.RunPython(clasificar_clinicas, migrations.RunPython.noop),
    ]
