# Generated by Django 6.0.4 on 2026-09-27 02:20

from django.db import migrations, models


def llenar_nombre_corto(apps, schema_editor):
    """La clinica estetica se muestra como 'Estética' donde no cabe su nombre completo."""
    Clinica = apps.get_model('core', 'Clinica')
    Clinica.objects.filter(tipo='estetica', nombre_corto='').update(nombre_corto='Estética')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nombre_centro_medicina_estetica'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=40),
        ),
        # Sin reversa de datos: al deshacer, la columna se elimina igual.
        migrations.RunPython(llenar_nombre_corto, migrations.RunPython.noop),
    ]
