# Generated by Django 6.0.4 on 2026-08-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
