# Generated by Django 6.0.4 on 2026-08-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacto',
            table='Contacto',
        ),
        migrations.AlterModelTable(
            name='expediente',
            table='Expediente',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
    ]
