# Generated by Django 6.0.4 on 2026-08-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_contacto_table_alter_expediente_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='parentesco_otro',
            field=models.CharField(blank=True, max_length=100, verbose_name='detalle si es "otro"'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='parentesco',
            field=models.CharField(choices=[('madre', 'Madre'), ('padre', 'Padre'), ('esposo', 'Esposo'), ('esposa', 'Esposa'), ('hijo', 'Hijo'), ('hija', 'Hija'), ('hermano', 'Hermano'), ('hermana', 'Hermana'), ('abuelo', 'Abuelo'), ('abuela', 'Abuela'), ('tio', 'Tío'), ('tia', 'Tía'), ('amigo', 'Amigo(a)'), ('vecino', 'Vecino(a)'), ('otro', 'Otro')], max_length=20),
        ),
    ]
