# Generated by Django 6.0.4 on 2026-08-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_contacto_parentesco_otro_alter_contacto_parentesco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='parentesco',
            field=models.CharField(choices=[('padre_madre', 'Padre/Madre'), ('esposo', 'Esposo(a)'), ('hijo', 'Hijo(a)'), ('hermano', 'Hermano(a)'), ('abuelo', 'Abuelo(a)'), ('tio', 'Tío(a)'), ('amigo', 'Amigo(a)'), ('vecino', 'Vecino(a)'), ('otro', 'Otro')], max_length=20),
        ),
    ]
