# Generated by Django 6.0.4 on 2026-08-30 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('doctor_nombre', models.CharField(blank=True, max_length=150)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('historia_enfermedad_actual', models.TextField(blank=True)),
                ('antecedentes', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('examen_fisico', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('indicaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.expediente')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('suero', 'Suero'), ('curacion', 'Curación'), ('nebulizacion', 'Nebulización'), ('otro', 'Otro')], max_length=15)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('indicaciones', models.TextField(blank=True)),
                ('ejecutada', models.BooleanField(default=False)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('ejecutada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones_ejecutadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='consultas.consulta')),
            ],
            options={
                'verbose_name': 'aplicación',
                'verbose_name_plural': 'aplicaciones',
            },
        ),
        migrations.CreateModel(
            name='ControlPosterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_control', models.DateField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'Atendido'), ('no_asistio', 'No asistió'), ('aplazado', 'Aplazado')], default='pendiente', max_length=15)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles', to='consultas.consulta')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'control posterior',
                'verbose_name_plural': 'controles posteriores',
            },
        ),
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('doctor_nombre', models.CharField(blank=True, max_length=150)),
                ('tipo', models.CharField(choices=[('incapacidad', 'Incapacidad'), ('constancia', 'Constancia médica')], max_length=15)),
                ('folio', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incapacidades', to='consultas.consulta')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'incapacidad o constancia',
                'verbose_name_plural': 'incapacidades y constancias',
            },
        ),
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('doctor_nombre', models.CharField(blank=True, max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('indicaciones', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_examen', to='consultas.consulta')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_examen', to='pacientes.persona')),
            ],
            options={
                'verbose_name': 'orden de examen',
                'verbose_name_plural': 'órdenes de examen',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_examen', models.CharField(max_length=150)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='consultas.ordenexamen')),
            ],
            options={
                'verbose_name': 'detalle de orden de examen',
                'verbose_name_plural': 'detalles de orden de examen',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('doctor_nombre', models.CharField(blank=True, max_length=150)),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receta', to='consultas.consulta')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=50)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='consultas.receta')),
            ],
            options={
                'verbose_name': 'detalle de receta',
                'verbose_name_plural': 'detalles de receta',
            },
        ),
        migrations.CreateModel(
            name='ReferenciaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('doctor_nombre', models.CharField(blank=True, max_length=150)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias', to='consultas.consulta')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'referencia médica',
                'verbose_name_plural': 'referencias médicas',
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('presion_arterial', models.CharField(blank=True, max_length=10)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('saturacion', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signos_vitales', to='consultas.consulta')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('tomado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signos_vitales_tomados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signos vitales',
                'verbose_name_plural': 'signos vitales',
            },
        ),
    ]
