# Generated by Django 6.0.4 on 2026-08-30 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aplicacion',
            table='Aplicacion',
        ),
        migrations.AlterModelTable(
            name='consulta',
            table='Consulta',
        ),
        migrations.AlterModelTable(
            name='controlposterior',
            table='ControlPosterior',
        ),
        migrations.AlterModelTable(
            name='detalleordenexamen',
            table='DetalleOrdenExamen',
        ),
        migrations.AlterModelTable(
            name='detallereceta',
            table='DetalleReceta',
        ),
        migrations.AlterModelTable(
            name='incapacidad',
            table='Incapacidad',
        ),
        migrations.AlterModelTable(
            name='ordenexamen',
            table='OrdenExamen',
        ),
        migrations.AlterModelTable(
            name='receta',
            table='Receta',
        ),
        migrations.AlterModelTable(
            name='referenciamedica',
            table='ReferenciaMedica',
        ),
        migrations.AlterModelTable(
            name='signosvitales',
            table='SignosVitales',
        ),
    ]
