# Generated by Django 6.0.4 on 2026-09-06 04:41

import uuid
from django.db import migrations, models


def asignar_solicitudes(apps, schema_editor):
    Incapacidad = apps.get_model('consultas', 'Incapacidad')
    for documento in Incapacidad.objects.using(schema_editor.connection.alias).all().iterator():
        documento.solicitud_id = uuid.uuid4()
        documento.save(update_fields=['solicitud_id'], using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_aplicacion_table_alter_consulta_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidad',
            name='clinica_direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='clinica_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='clinica_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='doctor_jvpm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='fecha_atencion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='paciente_nombre',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='solicitud_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(asignar_solicitudes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='incapacidad', name='solicitud_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
