# Generated by Django 6.0.4 on 2026-09-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_normalizar_incapacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidad',
            name='doctor_jvpm',
            field=models.CharField(blank=True, max_length=20, verbose_name='JVPM del emisor'),
        ),
    ]
