# Generated by Django 6.0.4 on 2026-09-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_incapacidad_doctor_jvpm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incapacidad',
            name='doctor_jvpm',
        ),
    ]
