# Generated by Django 6.0.4 on 2026-09-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_remove_incapacidad_doctor_jvpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
