# Generated by Django 6.0.4 on 2026-09-07 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0007_alter_consulta_inicio'),
        ('pacientes', '0005_alter_contacto_parentesco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('PATOLOGICO', 'Patológico'), ('ALERGICO', 'Alérgico'), ('QUIRURGICO', 'Quirúrgico'), ('GINECO', 'Gineco-obstétrico'), ('FAMILIAR', 'Familiar'), ('HABITOS', 'Hábitos'), ('OTRO', 'Otro')], max_length=15)),
                ('detalle', models.TextField()),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='antecedentes', to='pacientes.expediente')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'antecedente',
                'verbose_name_plural': 'antecedentes',
                'db_table': 'Antecedente',
                'ordering': ['tipo', '-fecha_creacion'],
            },
        ),
    ]
