# Generated by Django 6.0.4 on 2026-09-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0008_antecedente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
