# Generated by Django 6.0.4 on 2026-09-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0009_consulta_hora_llegada'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='es_emergencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consulta',
            name='motivo_prioridad',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
