# Generated by Django 6.0.4 on 2026-09-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0010_consulta_es_emergencia_consulta_motivo_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='nota_retiro',
            field=models.TextField(blank=True),
        ),
    ]
