# Generated by Django 6.0.4 on 2026-09-15 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0011_consulta_nota_retiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasignacionConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones', to='consultas.consulta')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('medico_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_cedidas', to=settings.AUTH_USER_MODEL)),
                ('medico_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('reasignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasignaciones_hechas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reasignación de consulta',
                'verbose_name_plural': 'reasignaciones de consulta',
                'db_table': 'ReasignacionConsulta',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
