# Generated by Django 6.0.4 on 2026-09-21 21:51

import consultas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0012_reasignacionconsulta'),
        ('pacientes', '0005_alter_contacto_parentesco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('archivo', models.FileField(upload_to=consultas.models.ruta_adjunto)),
                ('tipo', models.CharField(blank=True, choices=[('PDF', 'PDF'), ('IMAGEN', 'Imagen')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='pacientes.expediente')),
                ('modificado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'adjunto',
                'verbose_name_plural': 'adjuntos',
                'db_table': 'Adjunto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
