# Generated by Django 6.0.4 on 2026-10-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0013_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciamedica',
            name='hospital',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
