# Generated by Django 6.0.4 on 2026-08-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinica'),
        ('seguridad', '0003_extensiones_postgres'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clinicas',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='core.clinica'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='jvpm',
            field=models.CharField(blank=True, max_length=20, verbose_name='JVPM'),
        ),
    ]
