# Generated by Django 6.0.4 on 2026-08-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_clinica_table_alter_registroauditoria_table'),
        ('seguridad', '0004_usuario_clinicas_usuario_jvpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clinicas',
            field=models.ManyToManyField(blank=True, db_table='UsuarioClinica', related_name='usuarios', to='core.clinica'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
