# Generated by Django 6.0.4 on 2026-09-15 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clinica_tipo_tema'),
        ('seguridad', '0005_alter_usuario_clinicas_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.clinica'),
        ),
    ]
